services:
  - type: web
    name: bluebird-fence-quote
    env: static
    buildCommand: null
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Content-Type
        value: text/html
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.json
        name: Content-Type
        value: application/json
      - path: /*.jpg
        name: Content-Type
        value: image/jpeg
      - path: /*.png
        name: Content-Type
        value: image/png 